#!/bin/bash
output=$(find . -name "*.gif") output=$(echo "$output" | xargs file | grep "regular file" | cut -d ":" -f 1) output=$(echo "$output" | sed "s/.gif$//") output=$(echo "$output" | sort -f) echo "$output"
